import type { ProductViewModel } from "@/types/product";

const mockCatalog: Record<string, ProductViewModel[]> = {
  tech: [
    {
      slug: "hyperion-runtime",
      title: "Hyperion Runtime",
      subtitle: "v2.4.1 · WASM-native scheduler",
      primaryMeta: "12.4k",
      secondaryMeta: "3h ago",
      price: 99,
      currency: "$",
      badge: "Stable",
      available: true,
    },
    {
      slug: "sundial-db",
      title: "Sundial DB",
      subtitle: "Event-sourced PostgreSQL core",
      primaryMeta: "8.1k",
      secondaryMeta: "1d ago",
      price: 149,
      currency: "$",
      badge: "Beta",
      available: true,
    },
    {
      slug: "marrow-cli",
      title: "Marrow CLI",
      subtitle: "Config that ships itself",
      primaryMeta: "3.7k",
      secondaryMeta: "2d ago",
      price: 49,
      currency: "$",
      badge: "New",
      available: true,
    },
    {
      slug: "obsidian-panel",
      title: "Obsidian Panel",
      subtitle: "Air-gapped telemetry UI",
      primaryMeta: "5.2k",
      secondaryMeta: "1w ago",
      price: 199,
      currency: "$",
      badge: "Enterprise",
      available: false,
    },
  ],
  gaming: [
    {
      slug: "neon-katana",
      title: "Neon Katana",
      subtitle: "Energy blade · emits light in the dark",
      primaryMeta: "Epic",
      secondaryMeta: "5 left",
      price: 79,
      currency: "$",
      badge: "Drop",
      accentColor: "#B24FFF",
      available: true,
    },
    {
      slug: "void-runner-pack",
      title: "Void Runner Pack",
      subtitle: "Phantom mobility gear bundle",
      primaryMeta: "Rare",
      secondaryMeta: "38 left",
      price: 45,
      currency: "$",
      accentColor: "#4FA8FF",
      available: true,
    },
    {
      slug: "chroma-headset",
      title: "Chroma Headset",
      subtitle: "Spatial audio · squad sync",
      primaryMeta: "Legendary",
      secondaryMeta: "1 left",
      price: 320,
      currency: "$",
      accentColor: "#FFB800",
      available: true,
    },
    {
      slug: "starter-crate",
      title: "Starter Crate",
      subtitle: "Guaranteed common or better",
      primaryMeta: "Common",
      secondaryMeta: "In stock",
      price: 20,
      currency: "$",
      accentColor: "#8A8F98",
      available: true,
    },
  ],
  anime: [
    {
      slug: "yuki-last-ember",
      title: "Yuki, the Last Ember",
      subtitle: "Fire Caster · S-Rank",
      primaryMeta: "S-Rank",
      secondaryMeta: "Caster",
      price: 120,
      currency: "$",
      badge: "S",
      available: true,
    },
    {
      slug: "rin-foxblade",
      title: "Rin Foxblade",
      subtitle: "Scarlet Phantom",
      primaryMeta: "A-Rank",
      secondaryMeta: "Rogue",
      price: 95,
      currency: "$",
      badge: "A",
      available: true,
    },
    {
      slug: "momo-caramel",
      title: "Momo Caramel",
      subtitle: "Cosmic Barista",
      primaryMeta: "B-Rank",
      secondaryMeta: "Support",
      price: 65,
      currency: "$",
      badge: "B",
      available: true,
    },
  ],
  poetry: [
    {
      slug: "verse-laila",
      title: "سَلَامٌ على الديارِ وإنْ بدتْ لنا",
      subtitle: "مطلع قصيدة من العصر الأندلسي",
      primaryMeta: "الأندلسي",
      secondaryMeta: "الوافر",
      price: 30,
      currency: "$",
      badge: "معلقة",
      available: true,
    },
    {
      slug: "verse-imru",
      title: "قِفا نَبكِ من ذِكرى حبيبٍ ومَنزِلِ",
      subtitle: "من المعلقات السبع",
      primaryMeta: "الجاهلي",
      secondaryMeta: "الطويل",
      price: 45,
      currency: "$",
      badge: "معلقة",
      available: true,
    },
    {
      slug: "verse-abbasid",
      title: "سهرُ العيونِ وشوقُهنَّ شقاءُ",
      subtitle: "من الشعر العباسي",
      primaryMeta: "العباسي",
      secondaryMeta: "البسيط",
      price: 35,
      currency: "$",
      available: true,
    },
    {
      slug: "verse-modern",
      title: "يا ليتَ قومي يعلمونَ بأنَّني",
      subtitle: "قصيدة عصر النهضة",
      primaryMeta: "الحديث",
      secondaryMeta: "الكامل",
      price: 28,
      currency: "$",
      available: false,
    },
  ],
  football: [
    {
      slug: "karim-elmasry",
      title: "Karim Elmasry",
      subtitle: "Number 9 · Striker",
      primaryMeta: "92",
      secondaryMeta: "ST",
      price: 89,
      currency: "$",
      badge: "9",
      available: true,
    },
    {
      slug: "layla-rashidi",
      title: "Layla Rashidi",
      subtitle: "Playmaker",
      primaryMeta: "88",
      secondaryMeta: "CAM",
      price: 74,
      currency: "$",
      badge: "10",
      available: true,
    },
    {
      slug: "sami-boutaleb",
      title: "Sami Boutaleb",
      subtitle: "Sweeper Keeper",
      primaryMeta: "85",
      secondaryMeta: "GK",
      price: 59,
      currency: "$",
      badge: "1",
      available: true,
    },
    {
      slug: "zinedine-farouk",
      title: "Zinedine Farouk",
      subtitle: "Backline General",
      primaryMeta: "90",
      secondaryMeta: "CB",
      price: 69,
      currency: "$",
      badge: "5",
      available: false,
    },
  ],
  chess: [
    {
      slug: "ebony-king",
      title: "Ebony King",
      subtitle: "Hand-carved rosewood",
      primaryMeta: "Grandmaster",
      secondaryMeta: "Rosewood",
      price: 240,
      currency: "$",
      badge: "Limited",
      available: true,
    },
    {
      slug: "ivory-queen",
      title: "Ivory Queen",
      subtitle: "Bone finish",
      primaryMeta: "Classic",
      secondaryMeta: "Bone",
      price: 180,
      currency: "$",
      available: true,
    },
    {
      slug: "brass-rook",
      title: "Brass Rook",
      subtitle: "Solid brass",
      primaryMeta: "Tournament",
      secondaryMeta: "Brass",
      price: 95,
      currency: "$",
      badge: "New",
      available: true,
    },
    {
      slug: "obsidian-knight",
      title: "Obsidian Knight",
      subtitle: "Polished volcanic glass",
      primaryMeta: "Collector",
      secondaryMeta: "Obsidian",
      price: 310,
      currency: "$",
      available: false,
    },
  ],
};

export function getMockProducts(slug: string): ProductViewModel[] {
  return mockCatalog[slug] ?? [];
}
